# .github/workflows/server.yml
name: Server CI/CD

on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'
  pull_request:
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint or test
        run: echo "Add test command if needed"

      - name: Deploy or prepare backend
        run: echo "Deploy handled by Render/GitHub auto-deploy"
